
services:
  database:
    image: postgres:15-alpine
    container_name: tripnest-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: productionpassword
      POSTGRES_DB: tripnestdatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tripnest-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: tripnest-backend
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/tripnestdatabase
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=productionpassword
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - APP_JWT_SECRET=VHJpcE5lc3RWMlNlY3VyZUtleVRoYXRJczMyQnl0ZXNM
    ports:
      - "8080:8080"
    networks:
      - tripnest-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tripnest-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - tripnest-network

volumes:
  pgdata:

networks:
  tripnest-network:
    driver: bridge
